version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    container_name: backend
    command: bash -c "flask db upgrade && flask run --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/backend:cached

  nginx:
    build:
      context: nginx
      args:
        NGINX_CONFIG: nginx.dev.conf
    ports:
      - ${NGINX_PORTS}
    volumes:
      - static-files:/static
    container_name: nginx
    depends_on:
      - backend
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}

  db:
    image: postgres
    env_file:
      - .env

volumes:
  static-files:
