"""empty message

Revision ID: 0f1b2bdb5f87
Revises: dba3aa4d0d34
Create Date: 2018-11-08 14:59:51.453489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f1b2bdb5f87'
down_revision = 'dba3aa4d0d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('payu_order_id', sa.String(length=120), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('_payment_status', sa.Enum('NEW', 'PENDING', 'COMPLETED', 'REJECTED', 'CANCELED', name='payustatus'), nullable=True),
    sa.Column('_status', sa.Enum('NEW', 'PAID', 'SEND', 'FINISHED', 'CANCELED', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordered_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('revoked_token_model', sa.Column('jwi', sa.String(length=120), nullable=True))
    op.drop_column('revoked_token_model', 'jti')
    op.add_column('user', sa.Column('_roles', sa.Enum('ADMIN', 'SELLER', 'BUYER', name='role'), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'SELLER', 'BUYER', name='role'), autoincrement=False, nullable=True))
    op.drop_column('user', '_roles')
    op.add_column('revoked_token_model', sa.Column('jti', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('revoked_token_model', 'jwi')
    op.drop_column('item', 'price')
    op.drop_column('item', 'amount')
    op.drop_table('ordered_item')
    op.drop_table('order')
    # ### end Alembic commands ###
